name: check

on:
  schedule:
    - cron: 0 18 * * *
  watch:
    types: started
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查 v2ex.com
        run: |
          curl -v https://v2ex.com
