name: qiandao

on:
  schedule:
    - cron: '30 16 * * *'
  watch:
    types: started
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 开始
        env:
          v2ex: ${{ secrets.v2ex }}
          chh: ${{ secrets.chh }}
          hifi: ${{ secrets.hifi }}
        run: |
          cd src
          pip install --upgrade pip
          pip3 install requests
          python3 main.py
